### ISSUE TITLE
USER STORY 5: Explore relevant external research resources

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/BrightFuturesProject#5]
**User Story**

As a PARENT/TEACHER, I want to FIND RELEVANT LINKS to other research that support diversity and inclusion so that I can EXPLORE MORE IN-DEPTH information.

**Acceptance Criteria**

- [x] The website has a page dedicated to external research.
- [x] The research page utilises the Bootstrap grid and card components for consistency in layout and responsiveness..
- [x] The links are active and regularly updated.

**Tasks**

- [ ] Create a page for external research.
- [x] Create a responsive library featuring some relative external research websites
- [ ] Regularly update the links.
